example:
  message: "Dev Environment"
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/distributedb
    username: root
    password: root@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  application:
    name: inventory-service
